### ISSUE TITLE
[Query] How can you implement this with a StatefulWidget?

### ISSUE THREAD

**Issue by vzool** [deakjahn/flutter_isolate_web#1]
For instance, where should these lines to be:
```dart
worker.spawn(
  doWork,
  name: 'some-unique-name',
  onInitialized: onInitialized,
  onFromWorker: onReceive,
);
```

**Comment by deakjahn** [comment]
This has nothing to do with a `StatefulWidget` at all. You would probably call it from any handler or program logic function where you need the services of your isolate.

**Comment by vzool** [comment]
Yeah, but my use-case is an application run on Web and Mobile phones; it's handler-called when the user interacts with a button, which shows a progress bar then there is a long time-consuming process, then the user interface needs to track this process until it's done.

**Comment by deakjahn** [comment]
Then you simply use it just like you would use regular isolates in normal Flutter mobile projects, there's no difference to that.

It's by no means the only possible solution but in one of my apps, I need to have multiple parallel long operations. So, I created a stateful widget that displays the progress bar for each operation, and these widgets are put into a listview. Each widget handles a single operation (an upload in my particular case but this isn't important, of course). The isolate is spawned in the `onLayout()` function that I schedule from `initState()` as usual (I can't recall why not directly from the `initState()`, probably I needed the context at some point, you might try it directly, too):

    WidgetsBinding.instance?.addPostFrameCallback((_) => onLayout(context));

    void onLayout(BuildContext context) {
      globals.workers.spawn(
        Uploader.doWork,
        name: widget.item.GUID,
        onInitialized: doInitialize,
        onFromWorker: onCommand,
      );
    }

`doInitialize()`, `onCommand()` and all the rest are simply functions of this widget. The first instructs the isolate to start the actual work, the second receives any status reports and progress values from the isolate.  The `build()` shows the UI with the progress bar based on those values and also allows the user to cancel the operation. `Uploader` is a separate class that has the isolate code and does the heavy lifting.

The `dispose()` of the widget kills the isolate.
