### ISSUE TITLE
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'worker.js' is invalid.

### ISSUE THREAD

**Issue by vzool** [deakjahn/flutter_isolate_web#2]
Hi, I created `worker.js` at `project/web/worker.js` file with this content:

```js
onmessage = function(e) {
    console.log('Message: ', e);
    postMessage('Hello');
};
```
I updated `worker_web.dart` to with the following:
```dart
 static String source = "importScripts('worker.js');";
```
And I did get this error:
```js
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL 'worker.js' is invalid.
    at blob:http://localhost:63131/69d4c045-0884-490e-90b0-a1b983bd7934:1:1
```
Even though when in development mode I can access the file directly with no issue, like this: `http://localhost:63131/worker.js`, and still there is an error. Why?

**Comment by deakjahn** [comment]
Done: https://github.com/deakjahn/flutter_isolate_web/pull/3
